// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fable.Import.Firebase.Admin")>]
[<assembly: AssemblyProductAttribute("Fable.Import.Firebase")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for Firebase")>]
[<assembly: AssemblyVersionAttribute("0.0.5")>]
[<assembly: AssemblyFileVersionAttribute("0.0.5")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.Import.Firebase.Admin"
    let [<Literal>] AssemblyProduct = "Fable.Import.Firebase"
    let [<Literal>] AssemblyDescription = "Fable bindings for Firebase"
    let [<Literal>] AssemblyVersion = "0.0.5"
    let [<Literal>] AssemblyFileVersion = "0.0.5"
    let [<Literal>] AssemblyConfiguration = "Release"
